import * as dns from 'dns';
dns.setDefaultResultOrder('ipv4first');

import { connectDB } from '../src/repo/mongo.repo';
import { executeTwitterPost } from '../src/bot/telegram.bot';
import { config } from '../src/config/env.config';
import { logger } from '../src/utils/logger.util';
import * as twitterService from '../src/services/twitter';

async function runHappyPathTest() {
    const db = await connectDB();
    const counters = db.collection('daily_counters');
    const logs = db.collection('actions_log');
    const dateStr = new Date().toISOString().split('T')[0];

    // Clear state
    await counters.deleteMany({ date: dateStr });
    
    // Stub the twitter client via global
    (global as any).MOCK_TWITTER = {
        postTweet: async (text: string) => {
            return 'staging_test_12345';
        }
    };

    // 1. Create a mock draft in actions_log (as if generated by AI and pending)
    const { ObjectId } = require('mongodb');
    const mockDbId = new ObjectId().toString();
    await logs.insertOne({ _id: new ObjectId(mockDbId), status: 'pending', content_text: 'Mock text', type: 'post' });

    const prevCounters = await counters.findOne({ date: dateStr, account_id: config.ACCOUNT_ID });
    const prevPostsToday = prevCounters?.posts_today || 0;

    // 2. Call the real approve path function
    await executeTwitterPost(mockDbId, 'Mock text', 'post', {});

    // 3. Verify Database
    const finalLog = await logs.findOne({ _id: new ObjectId(mockDbId) });
    const finalCounters = await counters.findOne({ date: dateStr, account_id: config.ACCOUNT_ID });
    const newPostsToday = finalCounters?.posts_today || 0;

    console.log('\n--- TEST RESULTS ---');
    console.log(`actions_log.status == '${finalLog?.status}'`);
    console.log(`actions_log.tweet_id == '${finalLog?.tweet_id}'`);
    console.log(`daily_counters.posts_today == ${newPostsToday} (was ${prevPostsToday}, incremented by ${newPostsToday - prevPostsToday})`);
    
    if (finalLog?.status === 'posted' && finalLog?.tweet_id === 'staging_test_12345' && newPostsToday === prevPostsToday + 1) {
        console.log('RESULT: PASS');
    } else {
        console.log('RESULT: FAIL');
    }

    process.exit(0);
}

runHappyPathTest().catch(console.error);
